### ISSUE TITLE
TEXT not usable on non-win32 systems

### ISSUE THREAD

**Issue by GoogleCodeExporter** [smashedpumpkin/bin2h#3]
```
Hey.

I am trying to use bin2h in a project. But it depends on the TEXT macro... How 
can I use bin2h on a UNIX based os, which does not define said macro?

Kind regards!
```

Original issue reported on code.google.com by `ingwie2...@googlemail.com` on 31 Jan 2014 at 3:31

**Comment by smashedpumpkin** [comment]
Most *nix's already have a bin2h tool included in the distro, I would suggest using that for convenience instead of compiling your own. 

I'll look into having this compile on UNIX when I have some time all the same.
